sudo: required
services:
        - docker

before_install:
        - docker build -t reactapp/frontend -f Dockerfile.dev .        
script: 
        - docker run reactapp/frontend npm run test -- --coverage 

