sudo: required
services:
        - docker

before_install:
        - docker build -t MyImage/frontend -f Dockerfile.dev .        
script: 
        - docker run MyImage/frontend npm run test -- --coverage 

