sudo: required
services:
        - docker

before_install:
        - docker build -t reactapp/frontend -f Dockerfile.dev .        
script: 
        - docker run reactapp/frontend npm run test -- --coverage 

deploy: 
 edge: true
 provider: elasticbeanstalk
 region: "eu-central-1"
 app: "ReactApp"
 env: "Reactapp-env"
 bucket_name: "elasticbeanstalk-eu-central-1-497579936533"
 bucket_path: "ReactApp"
 on:
       branch: master
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key:
            secure: "$AWS_SECRET_KEY" 
        

